### ISSUE TITLE
Stakeholder draft matrix

### ISSUE THREAD

**Issue by rawrool** [rawrool/Group7_SmartGarden#4]

**Comment by JosetheJedi** [comment]
The link to the matrix.

https://docs.google.com/spreadsheets/d/1p_rMyBInPji7N1Spk-4h-voNm1IryV49Dm7rrz-wdcU/edit?usp=sharing

**Comment by rawrool** [comment]
I finished the stakeholder matrix. 
Updated link: https://drive.google.com/open?id=1Mm4sz3nHGqjPRfd5WV1FNIp13TLgUaqBrV9F-azy87I

**Comment by JosetheJedi** [comment]
I like it! Can you give the stakeholder information doc the same style?

**Comment by rawrool** [comment]
I'll give them more influence, but like I had mentioned on Slack the project is being made for garden owners. And, I understand as well that Agriculturists would also benefit and could provide input that could improve our project.

Yes, I'll edit that one after fixing this one.

**Comment by rawrool** [comment]
Alright, I edited the stakeholder matrix specifically the detail in the Authority column.

Someone review again.

**Comment by rawrool** [comment]
Based on everyone's feedback I will label this as done.
