### ISSUE TITLE
Create backend for user login in iOS app

### ISSUE THREAD

**Issue by akagopher8** [rawrool/Group7_SmartGarden#57]
Create a working backend so users can actually login to the iOS application.

**Comment by akagopher8** [comment]
Researching to learn more about user authentication from iOS to server with JSON web tokens and talking with Jose about what we currently have on our backend. 2 hours

**Comment by akagopher8** [comment]
Figuring out how to extract and save the web token from the response from the server so that even when the app is closed it persists on the device. And miscellaneous syntax research and MVC research 3 hours.

**Comment by akagopher8** [comment]
Getting an error when trying to send the request to our server. It is throwing:"-[SmartGarden.LoginViewController test:]: unrecognized selector sent to instance 0x7f8a4950d670" and "*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SmartGarden.LoginViewController test:]: unrecognized selector sent to instance 0x7f8a4950d670'"

 Looking for the cause and the solution currently.

**Comment by akagopher8** [comment]
Fixed the bug that was crashing the app and throwing the errors above. Had to delete the reference to test function created in class to show the professor how easy it is to link a button tap to a function. Getting the token still is not working however so working on that now. 
2 hours

**Comment by JosetheJedi** [comment]
How are you sending the data?

**Comment by akagopher8** [comment]
I fixed it. It was working the whole time to get the token. The variable that it was in was named differently than what I read everywhere else.

**Comment by akagopher8** [comment]
Fixed/Figured out a way to store the username and token for future queries. 4 hours
